extends Node

## Every sound in the game, generated by tools/make_sounds.py. Nothing here is
## decoration: the drone is the room, the heartbeat is the wick running out, and
## `caught` is the mechanic firing. A player who is not looking at the right
## corner of the screen still hears the maze move.

const ONE_SHOTS := {
	&"step_a": "res://audio/step_a.wav",
	&"step_b": "res://audio/step_b.wav",
	&"caught": "res://audio/caught.wav",
	&"oil": "res://audio/oil.wav",
	&"escaped": "res://audio/escaped.wav",
	&"burnt_out": "res://audio/burnt_out.wav",
}

const LOOPS := {
	&"drone": "res://audio/drone.wav",
	&"heartbeat": "res://audio/heartbeat.wav",
}

const DOOR := "res://audio/door.wav"

var _cache := {}
var _pool: Array[AudioStreamPlayer] = []
var _loops := {}


func _ready() -> void:
	for _i in 8:
		var player := AudioStreamPlayer.new()
		add_child(player)
		_pool.append(player)
	for key in LOOPS:
		var player := AudioStreamPlayer.new()
		player.stream = looped(LOOPS[key])
		add_child(player)
		_loops[key] = player


## A .wav imported by Godot does not loop by default and there is no way to say
## otherwise from a hand-written project, so the loop points are set here.
func looped(path: String) -> AudioStreamWAV:
	var stream: AudioStreamWAV = (load(path) as AudioStreamWAV).duplicate()
	stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
	stream.loop_begin = 0
	stream.loop_end = _frame_count(stream)
	return stream


func door_stream() -> AudioStreamWAV:
	return looped(DOOR)


func _frame_count(stream: AudioStreamWAV) -> int:
	var width := 2 if stream.format == AudioStreamWAV.FORMAT_16_BITS else 1
	var channels := 2 if stream.stereo else 1
	return stream.data.size() / (width * channels)


func play(key: StringName, volume_db := 0.0, pitch := 1.0) -> void:
	if not ONE_SHOTS.has(key):
		return
	if not _cache.has(key):
		_cache[key] = load(ONE_SHOTS[key])
	for player in _pool:
		if not player.playing:
			player.stream = _cache[key]
			player.volume_db = volume_db
			player.pitch_scale = pitch
			player.play()
			return


func loop(key: StringName, on: bool, volume_db := 0.0) -> void:
	var player: AudioStreamPlayer = _loops.get(key)
	if player == null:
		return
	player.volume_db = volume_db
	if on and not player.playing:
		player.play()
	elif not on and player.playing:
		player.stop()


func stop_all_loops() -> void:
	for player in _loops.values():
		player.stop()
